#!/usr/bin/env bash
## /etc/inputrc - global inputrc for libreadline
## conf for $HOME/.inputrc
# See readline(3readline) and `info rluserman' for more information.
Control-t: 'klock \n'
Control-o: 'cd $(lf -print-last-dir); \n'
Control-p: 'sed -n l;\n' 
Control-q: '\e[1~\nexit;\n'
Control-x: 'exec bash\n'
Control-h: '\e\e\n\\printf "\\e[A\\e[7m\\e[0K$HISTFILE\\n"; search_history\n'

"\eq": '\e[1~\nexit;\n'
Control-c: "\ec"

"\e[5~": 'hh\n'
"\e^A"": 'quoted-insert '





##############################
## CONFIF CHOICES ############
# When listing completions, readline displays the common prefix of the set of possible completions using a different color
# The color definitions are taken from the value of the LS_COLORS environment variable
# If there is a color definition in $LS_COLORS for the custom suffix "readline-colored-completion-prefix", readline uses this color for the common prefix instead of its default
set colored-completion-prefix on
# Enable tab-completion regardless of filename case
set completion-ignore-case on
# Treats hyphens (-) and underscores (_) as equivalent when performing case-insensitive filename matching and completion
set completion-map-case off
# Common prefixes longer than 5 are replaced with an ellipsis when displaying possible completions
set completion-prefix-display-length 2
# Enable returning up to 500 tab-completions without having to be asked
set completion-query-items 500
# Don't expand the home dir tilde (~)
set expand-tilde on
# Scroll text horizontally on a single line when longer than the width of the screen, instead of wrapping onto a new line
# set horizontal-scroll-mode on
# Display the common prefix of the list of possible completions (which may be empty) before cycling through the list
set menu-complete-display-prefix on
# Attempt to place the cursor position at the same location on each history line retrieved with previous-history or next-history
set history-preserve-point on
# Tab-completed directory names have a slash appended
set mark-directories on
# Immediately add a trailing slash when tab-completing symlinks to directories
set mark-symlinked-directories on
# Do not tab-complete hidden files unless the pattern explicitly begins with a dot
set match-hidden-files on
# Turn off the use of the internal pager when returning long tab-completion lists
set page-completions on
# Display completions with matches sorted horizontally in alphabetical order, rather than down the screen
set print-completions-horizontally on
# Only require single tab key press for tab-completion
# (Default is double tab key press)
set show-all-if-ambiguous on
set show-all-if-unmodified on
set skip-completed-text on
# Colored file types
set colored-stats on
# Suffix each returned file tab-completion with a character denoting its type
set visible-stats on
##############################
##############################
## --v-- ORIGINAL BELOW --v-- #### 
# Be 8 bit clean.
set input-meta on
set output-meta on
# To allow the use of 8bit-characters like the german umlauts, uncomment
# the line below. However this makes the meta key not work as a meta key,
# which is annoying to those which don't need to type in 8-bit characters.
set convert-meta off
# try to enable the application keypad when it is called.  Some systems
# need this to enable the arrow keys.
set enable-keypad on
# see /usr/share/doc/bash/inputrc.arrows for other codes of arrow keys
# do not bell on tab-completion
set bell-style none
set bell-style visible
# make autocompletion case insensitive and display suggestions
set completion-ignore-case On
set show-all-if-ambiguous On
# some defaults / modifications for the emacs mode
$if mode=emacs
# allow the use of the Home/End keys
"\e[1~": beginning-of-line
"\e[4~": end-of-line
# allow the use of the Delete/Insert keys
"\e[3~": delete-char
"\e[2~": quoted-insert
# mappings for "page up" and "page down" to step to the beginning/end
# of the history
# "\e[5~": beginning-of-hist
# "\e[6~": end-of-history
# alternate mappings for "page up" and "page down" to search the history
"\e[6~": history-search-forward
# mappings for Ctrl-left-arrow and Ctrl-right-arrow for word moving
"\e[1;5C": forward-word
"\e[1;5D": backward-word
"\e[5C": forward-word
"\e[5D": backward-word
"\e\e[C": forward-word
"\e\e[D": backward-word
$if term=rxvt
"\e[7~": beginning-of-line
"\e[8~": end-of-line
"\eOc": forward-word
"\eOd": backward-word
$endif
# for non RH/Debian xterm, can't hurt for RH/Debian xterm
# "\eOH": beginning-of-line
# "\eOF": end-of-line
# for freebsd console
# "\e[H": beginning-of-line
# "\e[F": end-of-line
$endif
#!/bin/bash
#Control-r: 'hh \n'
#Control-x: 'exec bash \n'
#Control-z: 'bg \n'

Control-t: 'klock \n'
Control-o: 'cd $(lf -print-last-dir); \n'
Control-d: '\n exit \n'
Control-p: 'sed -n l;\n' 
# Control-d: 'kill-whole-line;\nexit;\n'
Control-q: 'kill-whole-line;\nexit;\n'
Control-x: 'exec bash\n'
Control-h: 'hh\n'
"\eq": 'kill-whole-line;\nexit;\n'
# Control-s: 'history -a; history -n; printf "history \e[35m$HISTFILE\e[0m"; \ncat $HISTFILE|tac|fzf -m --no-sort --height 22";'
"\ep": "export PATH=${PATH}\e\C-e\"\C-a\ef\ef\C-f:\C-b\""
# Control-s: 'history -a; history -n; cat $HISTFILE|tac|fzf -m --no-sort --height 22 --header "$HISTFILE / ";'
"\eh": 'kill-whole-line;\nsearch_history\n'

# Cortrol-l 
# kdm bash-env
# .inputrc
# Cheatsheet
#
# https://man.archlinux.org/man/readline.3
"\e1": dump-functions
# "\es": 'printf "\e[A\e[K\e[8B\e[8A\e\n\n[2m --$re search folder: ";\n read -re  -i "$PWD" "ss"; kk=($(ls $ss|fzf -m --height 62% --header " -- $ss --"));\n printf "$dim --$re SELECTED: \n\n${kk[*]}\n\n$dim --$re variable$dim=$re\$kk \n\n"; \n '
"\es": '\nserch\n'
"\e2": dump-variables
"\e3": dump-macros
set show-mode-in-prompt off
# bind -l: List functions
#bind -p`  : List functions      and bindings
#`bind C-v`  : List variable names and values

#See actual character input coming into the terminal"
# Delete-forward : Delete following character


"\e[3~": delete-char
# Page up : Move backwards through completion history
#"\e[5~": history-search-backward
# Page down : Move forwards through completion history
#"\e[6~": history-search-forward
# F5 : Reload ~/.inputrc
"\e[15~": re-read-init-file
# F6 :
"\e[17~":
# Shift + space : Just do a space
"\e[32;2u": " "
#Shift + left/right arrow : move backward/forward by a word
"\e[1;5C": forward-word
"\e[1;5D": backward-word
# Option + left/right arrow : move backward/forward by a word
"\e[1;9C": forward-word
"\e[1;9D": backward-word
# Option + backspace : Delete previous word
# Option + delete-forward : Delete word
"\e[127;3u": shell-backward-kill-word
"\e[3;3~": shell-kill-word
# Option + c : Capitalize current word
"\ec": capitalize-word
"\ez": 'cd -\015'
# Option + l : lowercase current word
"\el": downcase-word
 Option + u : UPPERCASE current word
"\eu": upcase-word
# Option + p : Edit PATH variable
# Option + x : Change dir to last word of last command and run 'lll'
"\ex": 'cd !$ \015lll\015'
# Option + z : Undo a dir change
# Allow UTF-8 input and output, instead of showing stuff like $'\0123\0456'
set convert-meta on
set input-meta   on
set output-meta  on
# Do not bell on tab-completion
set bell-style none
# Attempt to briefly move the cursor to an opening parenthesis when a closing parenthesis is inserted
set blink-matching-paren off
# When listing completions, readline displays the common prefix of the set of possible completions using a different color
# The color definitions are taken from the value of the LS_COLORS environment variable
# If there is a color definition in $LS_COLORS for the custom suffix "readline-colored-completion-prefix", readline uses this color for the common prefix instead of its default
set colored-completion-prefix on
# Enable tab-completion regardless of filename case
set completion-ignore-case on
# Treats hyphens (-) and underscores (_) as equivalent when performing case-insensitive filename matching and completion
set completion-map-case off
# Common prefixes longer than 5 are replaced with an ellipsis when displaying possible completions
set completion-prefix-display-length 6
# Enable returning up to 500 tab-completions without having to be asked
set completion-query-items 500
# Don't expand the home dir tilde (~)
set expand-tilde on
# Scroll text horizontally on a single line when longer than the width of the screen, instead of wrapping onto a new line
# set horizontal-scroll-mode on
# Display the common prefix of the list of possible completions (which may be empty) before cycling through the list
set menu-complete-display-prefix on
# Attempt to place the cursor position at the same location on each history line retrieved with previous-history or next-history
set history-preserve-point on
# Tab-completed directory names have a slash appended
set mark-directories on
# Immediately add a trailing slash when tab-completing symlinks to directories
set mark-symlinked-directories on
# Do not tab-complete hidden files unless the pattern explicitly begins with a dot
set match-hidden-files on
# Turn off the use of the internal pager when returning long tab-completion lists
set page-completions on
# Display completions with matches sorted horizontally in alphabetical order, rather than down the screen
set print-completions-horizontally on
# Only require single tab key press for tab-completion
# (Default is double tab key press)
set show-all-if-ambiguous on
set show-all-if-unmodified on
set skip-completed-text on
# Colored file types
set colored-stats on
# Suffix each returned file tab-completion with a character denoting its type
set visible-stats on
# Include global inputrc files
$include /etc/inputrc
#$include /usr/local/etc/inputrc
#$include /opt/homebrew/etc/inputrc
